/**
 * build-embed.js
 *
 * Generates embed.html from index.html by injecting the embed-overrides CSS
 * block right after the <meta name="viewport"> tag. This lets iframe embeds
 * render borderless/transparent without maintaining a second copy of the file.
 *
 * Usage:
 *   node build-embed.js
 *
 * Also wired into package.json ("build" script) and vercel.json so Vercel
 * runs it automatically on every deploy.
 *
 * WORKFLOW:
 *   1. Edit index.html only (source of truth)
 *   2. git push
 *   3. Vercel runs `npm run build` → regenerates embed.html → deploys both
 *
 * You should NEVER hand-edit embed.html. Any changes there will be overwritten.
 */

const fs = require('fs');
const path = require('path');

const ROOT = __dirname;
const SOURCE = path.join(ROOT, 'index.html');
const OVERRIDES = path.join(ROOT, 'embed-overrides.css');
const OUTPUT = path.join(ROOT, 'embed.html');

function build() {
    if (!fs.existsSync(SOURCE)) {
        console.error(`[build-embed] Missing source: ${SOURCE}`);
        process.exit(1);
    }
    if (!fs.existsSync(OVERRIDES)) {
        console.error(`[build-embed] Missing overrides: ${OVERRIDES}`);
        process.exit(1);
    }

    const html = fs.readFileSync(SOURCE, 'utf8');
    const css = fs.readFileSync(OVERRIDES, 'utf8').trim();

    // Wrap the CSS in a <style id="embed-overrides"> block so it's easy
    // to spot when inspecting the deployed embed.html in DevTools.
    const styleBlock = `<style id="embed-overrides">\n${css}\n</style>`;

    // Inject right after the <meta name="viewport"> tag.
    // If that tag isn't found we fall back to injecting after <head>.
    const viewportRegex = /(<meta\s+name="viewport"[^>]*>)/i;
    const headRegex = /(<head[^>]*>)/i;

    let output;
    if (viewportRegex.test(html)) {
        output = html.replace(viewportRegex, `$1\n${styleBlock}`);
    } else if (headRegex.test(html)) {
        output = html.replace(headRegex, `$1\n${styleBlock}`);
    } else {
        console.error('[build-embed] Could not find <head> or <meta name="viewport"> in index.html');
        process.exit(1);
    }

    // Add a generated-file banner so anyone inspecting embed.html knows
    // it's autogenerated and shouldn't be hand-edited.
    const banner = `<!--\n  AUTO-GENERATED FILE — do not edit.\n  Built from index.html + embed-overrides.css by build-embed.js.\n  Run: npm run build (or: node build-embed.js)\n-->\n`;
    output = output.replace(/^<!DOCTYPE html>/i, `<!DOCTYPE html>\n${banner}`);

    fs.writeFileSync(OUTPUT, output, 'utf8');

    const srcKb = (fs.statSync(SOURCE).size / 1024).toFixed(1);
    const outKb = (fs.statSync(OUTPUT).size / 1024).toFixed(1);
    console.log(`[build-embed] ✓ Generated embed.html (${outKb} KB) from index.html (${srcKb} KB)`);
}

build();
